### ISSUE TITLE
Bug: In auto_commit=False mode, the second message is processed when the processing of the first failed with an error

### ISSUE THREAD

**Issue by DABND19** [airtai/faststream#1980]
**Describe the bug**
In auto_commit=False mode, the second message is processed when the processing of the first failed with an error

**How to reproduce**
Include source code:

`main.py`:
```python
import logging

import faststream
import fast_depends
import pydantic
from faststream import confluent


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
broker = confluent.KafkaBroker(
    "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094",
    logger=logger,
    allow_auto_create_topics=False,
)
TOPIC_NAME = "sequence-events"


class Event(pydantic.BaseModel):
    sequence_number: int


class SomeService:
    def business_logic(self, sequence_number: int) -> None:
        logger.info("Sequence number: %d", sequence_number)


@broker.subscriber(
    TOPIC_NAME,
    auto_commit=False,
    retry=True,
    group_id="sequence-handler",
    auto_offset_reset="earliest",
)
async def handler(
    event: Event, service: SomeService = fast_depends.Depends(SomeService)
) -> None:
    if event.sequence_number % 2 != 0:
        raise ValueError("Sequence number must be even")
    service.business_logic(event.sequence_number)


app = faststream.FastStream(broker, logger=logger)


@app.after_startup
async def publish_stubs() -> None:
    stubs = [Event(sequence_number=i) for i in range(10)]
    await broker.publish_batch(*stubs, topic=TOPIC_NAME)

```

`docker-compose.yml`:
```yaml
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper
    ports:
      - 2181:2181
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:7.7.0
    ports:
      - "9092:9092"
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    depends_on:
      zookeeper:
        condition: service_healthy

  kafka-2:
    image: confluentinc/cp-kafka:7.7.0
    ports:
      - "9093:9093"
    healthcheck:
      test: nc -z localhost 9093 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-2:19093,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      zookeeper:
        condition: service_healthy

  kafka-3:
    image: confluentinc/cp-kafka:7.7.0
    ports:
      - "9094:9094"
    healthcheck:
      test: nc -z localhost 9094 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka-3:19094,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    depends_on:
      zookeeper:
        condition: service_healthy

  redpanda_console:
    image: redpandadata/console:latest
    ports:
      - "9090:8080"
    environment:
      - KAFKA_BROKERS=kafka-1:19092,kafka-2:19093,kafka-3:19094
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

```

And/Or steps to reproduce the behavior:

1. Create topic "sequence-events" in redpanda console

2. Run faststream application from main.py:
```bash
faststream run main:app
```

2. In the console, look at the offset of the topic, it will be equal to 9, although it should be equal to 0 or 1
