### ISSUE TITLE
Bug: the type for the new subscriber method parameter is not typed.

### ISSUE THREAD

**Issue by powersemmi** [airtai/faststream#2060]
**Describe the bug**
mypy indicates that it cannot find overloads with the new max_workers parameter.

**How to reproduce**
Include source code:

```python
import logging
from typing import Annotated, Any

from fast_depends import Depends

from .brokers import broker

logger = logging.getLogger(__name__)


@broker.subscriber(
    'sample',
    group_id='sample',
    max_workers=config.SEARCH_QUERY_BATCH,
)
async def sample(task: dict[Any, Any]) -> None:
    pass
```

And/Or steps to reproduce the behavior:

1. pip install mypy
2. mypy .

**Expected behavior**
mypy will be successful

**Observed behavior**
mypy finds a typing error

**Screenshots**

![Image](https://github.com/user-attachments/assets/bdd7306c-1085-43a2-824b-d364a56f73fd)

**Environment**
Running FastStream 0.5.34 with CPython 3.11.11 on Linux

**Additional context**

my mypy config
```toml
[tool.mypy]
plugins = ["pydantic.mypy"]
ignore_missing_imports = true
strict_optional = true
no_implicit_optional = true
disallow_any_generics = true
disallow_untyped_defs = true
strict_equality = true
warn_unreachable = true
warn_no_return = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
exclude = ["venv", "scripts", "tmp"]
```
