### ISSUE TITLE
Bug: Never returning request when something fails in the processing

### ISSUE THREAD

**Issue by pafi-code** [airtai/faststream#2074]
**Describe the bug**
So I wrote a service that has a queue available that does some processing. I used the `Router` to do so. When a message gets nacked the awaiting from `broker.request` get stuck.

**How to reproduce**

```python
from faststream import exceptions, FastStream, rabbit, TestApp
import pytest


async def process(value: int) -> int:
    if value >= 0:
        return value
    raise exceptions.NackMessage(requeue=False)


my_router = rabbit.RabbitRouter(
    handlers=(
        rabbit.RabbitRoute(
            process,
            queue="test-queue",
            exchange="test.exchange",
            publishers=(rabbit.RabbitPublisher(exchange="response.test.exchange"),),
        ),
    )
)
broker = rabbit.RabbitBroker(
    url="amqp://guest:guest@localhost:5672/",
)
broker.include_router(my_router)
app = FastStream(broker)


@pytest.mark.asyncio
async def test_positive_input():
    async with TestApp(app) as service:
        # works
        result = await service.broker.request(
            1, queue="test-queue", exchange="test.exchange"
        )
        assert result.body == b"1"


@pytest.mark.asyncio
async def test_negativ_input():
    async with TestApp(app) as service:
        # stuck
        result = await service.broker.request(
            -1, queue="test-queue", exchange="test.exchange"
        )
```

Given the code snippet above pytest fails.

**Expected behavior**
I would expect that I get a NackMessage or something like this back that I could check for.

**Environment**
RabbitMQ runs from this docker compose file:

```yaml
services:
  rabbitmq:
    image: rabbitmq:alpine
    ports:
    - published: ${RABBIT_PORT:-5672}
      target: 5672
    - published: ${RABBIT_UI_PORT:-15672}
      target: 15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    command: bash -c "rabbitmq-plugins enable rabbitmq_management && rabbitmq-server start"
```
